name: character_viewer
description: Flutter example project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # General
  provider: 6.0.5
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  go_router: 12.0.0

  # Networking
  http: 1.1.0


  # UI
  cached_network_image: 3.3.0

  # Code generators
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.0

  # Code generators
  build_runner: 2.4.6
  json_serializable: 6.7.1
  freezed: 2.4.5

flutter:
  uses-material-design: true
